name: fish_app_mari
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.2.0
  firebase_storage: ^8.0.5
  google_sign_in: ^5.0.2
  flutter_auth_buttons: ^0.10.0
  provider: ^5.0.0
  english_words: ^3.1.5
  image_picker: ^0.7.4

  
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
