name: fish_app_mari
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_storage: ^8.0.5
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.2
  flutter_auth_buttons: ^0.10.0
  provider: ^5.0.0
  image_picker: ^0.7.4
  english_words: ^3.1.5
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^2.0.1
  http: ^0.13.3
  json_serializable: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.10.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
